// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: microSui

#include "ui.h"

lv_obj_t * ui_Screen1 = NULL;
lv_obj_t * ui_balance = NULL;
lv_obj_t * ui_Label2 = NULL;
lv_obj_t * ui_address = NULL;
lv_obj_t * ui_Button1 = NULL;
lv_obj_t * ui_Image1 = NULL;
lv_obj_t * ui_Label4 = NULL;
// event funtions
void ui_event_Button1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Screen3, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_Screen3_screen_init);
    }
}

// build funtions

void ui_Screen1_screen_init(void)
{
    ui_Screen1 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_balance = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_balance, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_balance, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_balance, -1);
    lv_obj_set_y(ui_balance, -40);
    lv_obj_set_align(ui_balance, LV_ALIGN_CENTER);
    lv_label_set_text(ui_balance, "0");

    ui_Label2 = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_Label2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label2, 39);
    lv_obj_set_y(ui_Label2, -41);
    lv_obj_set_align(ui_Label2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label2, "SUI");

    ui_address = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_address, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_address, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_address, 24);
    lv_obj_set_y(ui_address, -61);
    lv_obj_set_align(ui_address, LV_ALIGN_CENTER);
    lv_label_set_text(ui_address, "0X00..00");

    ui_Button1 = lv_btn_create(ui_Screen1);
    lv_obj_set_width(ui_Button1, 100);
    lv_obj_set_height(ui_Button1, 30);
    lv_obj_set_x(ui_Button1, 1);
    lv_obj_set_y(ui_Button1, 60);
    lv_obj_set_align(ui_Button1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button1, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Button1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_text_color(ui_Button1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Button1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image1 = lv_img_create(ui_Screen1);
    lv_img_set_src(ui_Image1, &ui_img_suiicon_png);
    lv_obj_set_width(ui_Image1, LV_SIZE_CONTENT);   /// 50
    lv_obj_set_height(ui_Image1, LV_SIZE_CONTENT);    /// 51
    lv_obj_set_x(ui_Image1, -43);
    lv_obj_set_y(ui_Image1, -51);
    lv_obj_set_align(ui_Image1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image1, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label4 = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_Label4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label4, 0);
    lv_obj_set_y(ui_Label4, 61);
    lv_obj_set_align(ui_Label4, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label4, "GO ");

    lv_obj_add_event_cb(ui_Button1, ui_event_Button1, LV_EVENT_ALL, NULL);

}

void ui_Screen1_screen_destroy(void)
{
    if(ui_Screen1) lv_obj_del(ui_Screen1);

    // NULL screen variables
    ui_Screen1 = NULL;
    ui_balance = NULL;
    ui_Label2 = NULL;
    ui_address = NULL;
    ui_Button1 = NULL;
    ui_Image1 = NULL;
    ui_Label4 = NULL;

}
