#include <stdio.h>
#include <stdint.h>
#include <string.h>

#include "Client.h"

/// CONSTANTS
// RPC NODE Url (you can change it to mainnet or local node)
const char* rpc_url = "https://fullnode.testnet.sui.io:443/"; // Sui Testnet fullnode RPC URL
// Private key in Bech32 format
const char* sui_private_key_bech32 = "suiprivkey1qqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqq509duq"; // Example private key in Bech32 format
// Hardcoded transaction bytes (previously generated by Sui Typescript SDK) 
const char* message_string = "000002000800e1f5050000000000202e3d52393c9035afd1ef38abd7fce2dad71f0e276b522fb274f4e14d1df9747202020001010000010103000000000101007a1378aafadef8ce743b72e8b248295c8f61c102c94040161146ea4d51a182b6012901f275336715aa2d266fcdc57b3733fca4b135637160d6364acf4b7874590d0d0bd0140000000020a17f8121673e79df6e2070474050a4a4e3b51dee9887b90d87eafae9af4606257a1378aafadef8ce743b72e8b248295c8f61c102c94040161146ea4d51a182b6e80300000000000040ab3c000000000000";

int main(void) {
    printf("\n\t\t\t --- MicroSui Client DEMO ---");
    printf("\n\t This demo shows how to use the MicroSuiClient to send a transaction to the Sui Network.");
    printf("\n\t It uses a hardcoded transaction bytes previously generated by Sui Typescript SDK.\n");
    
    // Create a client connected to the Sui mainnet fullnode
    MicroSuiClient client = SuiClient_newClient(rpc_url);

    // Create a keypair from a given secret key in Bech32 format
    MicroSuiEd25519 keypair = SuiKeypair_fromSecretKey(sui_private_key_bech32);
    
    // Initialize a MicroSuiTransaction object from setPrebuiltTxBytes(...) constructor
    MicroSuiTransaction tx = SuiTransaction_setPrebuiltTxBytes(message_string);

    // Using method1 of the client: signAndExecuteTransaction (Simpler, creates the signature internally)
    SuiTransactionBlockResponse res1 = client.signAndExecuteTransaction(&client, keypair, tx);
    if (res1.digest == NULL) {
        printf("Error: No response from Sui Network\n");
        return -1;
    }
    printf("\n\n\t Sui Network RPC Response 1 (signAndExecuteTransaction method):\n\n");
    printf("\t Tx Digest= %s\n", res1.digest);
    printf("\t Tx Checkpoint= %s\n", res1.checkpoint);
    printf("\t Tx confirmedLocalExecution= %s\n", res1.confirmedLocalExecution);

    printf("\n\t\t Balance Changes: %d\n", res1.balanceChanges_len);
    for (int i = 0; i < res1.balanceChanges_len; i++)
    {
        printf("\t Balances Changes Coin %d:\n", i+1);
        printf("\t\t balanceChanges[%d].amount= %s\n", i, res1.balanceChanges[i].amount);
        printf("\t\t balanceChanges[%d].coinType= %s\n", i, res1.balanceChanges[i].coinType);
        printf("\t\t balanceChanges[%d].owner= %s\n", i, res1.balanceChanges[i].owner);
    }

    /// Method 2 to send Tx to Sui Network: executeTransactionBlock (More customizable, needs the signature as parameter):
    SuiSignature sig = keypair.signTransaction(&keypair, message_string); // We obtain the signature in base64 format
    SuiTransactionBlockResponse res2 = client.executeTransactionBlock(&client, tx.tx_bytes, sig);
    printf("\n\n\t Sui Network RPC Response 2 (executeTransactionBlock method)  -- Digest: %s (same)\n\n", res2.digest);


    // After each Sui Execute Transaction you must call tx.clear(&tx) (To avoid memory leaks)
    tx.clear(&tx); // VERY IMPORTANT STEP

    printf("\n\n\t\t --- END OF CLIENT DEMO ---\n");

    return 0;
}