#include <stdio.h>
#include <stdint.h>
#include <string.h>

#include "Transaction.h"

int main(void) {
    printf("\n\t\t\t --- MicroSui TRANSACTION DEMO ---");
    printf("\n\t This demo shows how to create a Sui Transaction, and how to manage it.");
    printf("\n\t For now only we can hardcode a prebuilded transaction data, but in the future we will be able to add operations and build it with BCS.\n");

    const char* message_string = "00000200080065cd1d0000000000202e3d52393c9035afd1ef38abd7fce2dad71f0e276b522fb274f4e14d1df974720202000101000001010300000000010100d79a4c7a655aa80cf92069bbac9666705f1d7181ff9c2d59efbc7e6ec4c3379d0180dc491e55e7caabfcdd1b0f538928d8d54107b9c1def3ed0baa3aa5106ba8674f0dd01400000000204b7e9da00f30cd1edf4d40710213c15a862e1fc175f2edb2b2c870c8559d65cdd79a4c7a655aa80cf92069bbac9666705f1d7181ff9c2d59efbc7e6ec4c3379de80300000000000040ab3c000000000000";
    
    // Initialize a MicroSuiTransaction object from setPrebuiltTxBytes(...) constructor
    printf("\n\tCreating TX1: a MicroSuiTransaction object from hardcoded bytes (previosly generated by Sui Typescript SDK)...\n");
    MicroSuiTransaction tx = SuiTransaction_setPrebuiltTxBytes(message_string);

    // Printing values
    printf("\n\tTransaction1 Bytes after Harcoded Init Constructor:\n");
    const uint8_t* tx_bytes = tx.tx_bytes.data;
    size_t tx_length = tx.tx_bytes.length;
    printf("\t\t Transaction1 Bytes Length: %zu\n", tx_length);
    printf("\t\t Transaction1 Bytes: ");
    for (size_t i = 0; i < tx_length; i++) {
        printf("%02x", tx_bytes[i]);
    }
    printf("\n");

    // Build the transaction (currently not performing any operation, just a placeholder)
    printf("\n\tBuilding Transaction1...\n");
    TransactionBytes built_tx_bytes = tx.build(&tx);
    printf("\t\t Transaction1 Bytes after Build Method: (show the same as before, this method is a placeholder for now, not BCS serialized yet)\n");
    printf("\t\t Built Transaction1 Bytes Length: %zu\n", built_tx_bytes.length);
    printf("\t\t Built Transaction1 Bytes: ");
    for (size_t i = 0; i < built_tx_bytes.length; i++) {
        printf("%02x", built_tx_bytes.data[i]);
    }
    printf("\n");



    // Initialize a MicroSuiTransaction object from init(...) constructor
    printf("\n\n\t Creating TX2: a MicroSuiTransaction object from clean init...");
    printf("\n\t This is a clean transaction, without any bytes, just to show how to use the build method...");
    printf("\n\t However is not possible to build a transaction in MicroSui yet, we need implement the BCS serialization and the transaction operations first,");
    printf(" so this example just shows how to use the build method, but it will return NULL for now.\n");

    MicroSuiTransaction tx2 = SuiTransaction_init();
    size_t tx2_length = tx2.tx_bytes.length;
    printf("\n\t Transaction2 Bytes Length: %zu\n", tx2_length);
    

    printf("\n\n\t\t --- END OF TRANSACTION DEMO ---\n");

    return 0;
}