// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui.h"

lv_obj_t * ui_Screen2 = NULL;
lv_obj_t * ui_lock = NULL;
lv_obj_t * ui_swLight = NULL;
lv_obj_t * ui_swFan = NULL;
lv_obj_t * ui_swTv = NULL;
lv_obj_t * ui_Label6 = NULL;
lv_obj_t * ui_Label7 = NULL;
lv_obj_t * ui_Label8 = NULL;
lv_obj_t * ui_swSpeaker = NULL;
lv_obj_t * ui_Label9 = NULL;
// event funtions
void ui_event_Screen2(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_LEFT) {
        lv_indev_wait_release(lv_indev_get_act());
        _ui_screen_change(&ui_Screen1, LV_SCR_LOAD_ANIM_MOVE_LEFT, 100, 0, &ui_Screen1_screen_init);
    }
}

void ui_event_lock(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        (e);
    }
}

// build funtions

void ui_Screen2_screen_init(void)
{
    ui_Screen2 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_lock = lv_imgbtn_create(ui_Screen2);
    lv_imgbtn_set_src(ui_lock, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_lock_png, NULL);
    lv_imgbtn_set_src(ui_lock, LV_IMGBTN_STATE_PRESSED, NULL, &ui_img_unlock_png, NULL);
    lv_imgbtn_set_src(ui_lock, LV_IMGBTN_STATE_CHECKED_PRESSED, NULL, &ui_img_unlock_png, NULL);
    lv_imgbtn_set_src(ui_lock, LV_IMGBTN_STATE_CHECKED_RELEASED, NULL, &ui_img_lock_png, NULL);
    lv_obj_set_width(ui_lock, 40);
    lv_obj_set_height(ui_lock, 51);
    lv_obj_set_x(ui_lock, 0);
    lv_obj_set_y(ui_lock, -70);
    lv_obj_set_align(ui_lock, LV_ALIGN_CENTER);

    ui_swLight = lv_switch_create(ui_Screen2);
    lv_obj_set_width(ui_swLight, 50);
    lv_obj_set_height(ui_swLight, 25);
    lv_obj_set_x(ui_swLight, 41);
    lv_obj_set_y(ui_swLight, -16);
    lv_obj_set_align(ui_swLight, LV_ALIGN_CENTER);

    ui_swFan = lv_switch_create(ui_Screen2);
    lv_obj_set_width(ui_swFan, 50);
    lv_obj_set_height(ui_swFan, 25);
    lv_obj_set_x(ui_swFan, 42);
    lv_obj_set_y(ui_swFan, 17);
    lv_obj_set_align(ui_swFan, LV_ALIGN_CENTER);

    ui_swTv = lv_switch_create(ui_Screen2);
    lv_obj_set_width(ui_swTv, 50);
    lv_obj_set_height(ui_swTv, 25);
    lv_obj_set_x(ui_swTv, 43);
    lv_obj_set_y(ui_swTv, 48);
    lv_obj_set_align(ui_swTv, LV_ALIGN_CENTER);

    ui_Label6 = lv_label_create(ui_Screen2);
    lv_obj_set_width(ui_Label6, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label6, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label6, -31);
    lv_obj_set_y(ui_Label6, -16);
    lv_obj_set_align(ui_Label6, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label6, "Light");

    ui_Label7 = lv_label_create(ui_Screen2);
    lv_obj_set_width(ui_Label7, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label7, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label7, -29);
    lv_obj_set_y(ui_Label7, 16);
    lv_obj_set_align(ui_Label7, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label7, "Fan");

    ui_Label8 = lv_label_create(ui_Screen2);
    lv_obj_set_width(ui_Label8, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label8, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label8, -30);
    lv_obj_set_y(ui_Label8, 49);
    lv_obj_set_align(ui_Label8, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label8, "TV");

    ui_swSpeaker = lv_switch_create(ui_Screen2);
    lv_obj_set_width(ui_swSpeaker, 50);
    lv_obj_set_height(ui_swSpeaker, 25);
    lv_obj_set_x(ui_swSpeaker, 43);
    lv_obj_set_y(ui_swSpeaker, 80);
    lv_obj_set_align(ui_swSpeaker, LV_ALIGN_CENTER);

    ui_Label9 = lv_label_create(ui_Screen2);
    lv_obj_set_width(ui_Label9, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label9, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label9, -29);
    lv_obj_set_y(ui_Label9, 81);
    lv_obj_set_align(ui_Label9, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label9, "Speaker");

    lv_obj_add_event_cb(ui_lock, ui_event_lock, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Screen2, ui_event_Screen2, LV_EVENT_ALL, NULL);

}

void ui_Screen2_screen_destroy(void)
{
    if(ui_Screen2) lv_obj_del(ui_Screen2);

    // NULL screen variables
    ui_Screen2 = NULL;
    ui_lock = NULL;
    ui_swLight = NULL;
    ui_swFan = NULL;
    ui_swTv = NULL;
    ui_Label6 = NULL;
    ui_Label7 = NULL;
    ui_Label8 = NULL;
    ui_swSpeaker = NULL;
    ui_Label9 = NULL;

}
